### ISSUE TITLE
Key issues

### ISSUE THREAD

**Issue by Kennochas** [raiguard/Factorio-FluidMustFlow#9]
### Description

Hello,

I installed this mod today with space exploration, and see the following for a few of the items:

unknown key: entity.description.duct-small.... etc, when hovering the item for description.

Looking at the locale files, it seems that en.cfg is missing some descriptions. Seems like the en.cfg is quite a bit shorter than other language files to be honest.

### Reproduction

1. Research the new entities added by the mod.
2. Check the description of said items.

### Factorio version

latest

### In-game username

Kennocha

**Comment by raiguard** [comment]
Space Exploration is causing this issue. They add a bit to the entity descriptions that says they cannot be placed on land / space. Since the items don't have descriptions, it shows unknown key.

The Factorio devs would need to add a feature to not show that unknown key message in order for this to be fixed.
